name: CI
on:
  push:
    branches: [ "jpassing-master-v1.23" ]
  pull_request:
    branches: [ "jpassing-master-v1.23" ]

jobs:
  build:
    runs-on: windows-2025
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run
      shell: pwsh
      run: |
        # https://github.com/jpassing/windows-terminal?tab=readme-ov-file#building-the-code
        Import-Module .\tools\OpenConsole.psm1
        Set-MsBuildDevEnvironment
        Invoke-OpenConsoleBuild
        